# all:
# 	g++ tournament.cpp -c -std=c++11
# 	gcc gfx.c -c
# 	g++ main.cpp tournament.o gfx.o -o main -std=c++11 -lX11

all:
	g++ tournament.cpp -c -std=c++11
	g++ test.cpp tournament.o -o test -std=c++11